<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\GeneralizeQueries.Core\GeneralizeQueries.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8"/>
        <PackageReference Include="MongoDB.Bson" Version="3.5.0"/>
        <PackageReference Include="MongoDB.Driver" Version="3.5.0"/>
        <PackageReference Include="Platform.Infrastructure.Core" Version="1.0.30"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
