<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0-rc.1.25451.107"/>
        <PackageReference Include="MongoDB.Bson" Version="3.5.0"/>
        <PackageReference Include="MongoDB.Driver" Version="3.5.0"/>
        <PackageReference Include="Platform.Infrastructure.Authentication" Version="1.0.15"/>
        <PackageReference Include="Platform.Infrastructure.Core" Version="1.0.30"/>
        <PackageReference Include="Platform.Infrastructure.Host.WebApi" Version="1.0.11"/>
        <PackageReference Include="Platform.Infrastructure.MassTransit.Bus.RabbitMQ" Version="1.0.12"/>
        <PackageReference Include="Platform.Infrastructure.ServiceRegistration.Provider" Version="1.0.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GeneralizeQueries.Application\GeneralizeQueries.Application.csproj"/>
        <ProjectReference Include="..\GeneralizeQueries.Infrastructure\GeneralizeQueries.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
